# -*- coding: utf-8 -*-
"""graph_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWOWH5duCRvXgCpYj1z8iS0vrnvo_s9e
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("./face_dataset.csv")

emotions = []


# obtain emotions array
for i, entity in df.iterrows():
    emotions.append(entity['emotion'])

    # print(entity)

emotions = np.array(emotions)
dtype = emotions.dtype
print(f'shape of emotions array: {emotions.shape}, dtype={dtype}')

# obtain images pixels
pixels = df.iloc[:, 1:].values

images_pixels = []
for image_pixels_str in pixels:
    img = image_pixels_str[0].split()
    img = [int(pixel) for pixel in img]
    images_pixels.append(img)

print(f'image pixels shape: {len(images_pixels)}:{len(images_pixels[0])}, dtype={type(images_pixels[0])}')
print(images_pixels[0])

df = {
  'emotions': emotions,
  'images_pixels': images_pixels }

df = pd.DataFrame(df)
# df

# df['images_pixels']

# plotting n images



emotions = df['emotions']

image_list = df['images_pixels']
image_shape = (48, 48)

selected_images = []

count = 64
for i in range(count):
  img = np.array(image_list[i])
  img = img.reshape(image_shape)
  selected_images.append(img)


fig, axs = plt.subplots(8, 8)


for i, ax in enumerate(axs.flat):
    ax.imshow(selected_images[i], cmap='gray')
    ax.axis('off')  # Hide axes
    ax.set_title(f'{emotions[i]}')  # Set title


plt.tight_layout()

plt.show()

# categorize images into groups
emotions = df['emotions']

count_image_categories = {
    '0': 0,
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
}

not_48_48_images_index = []
for i, image in enumerate(image_list):

    try:
        img = np.array(image).reshape(image_shape)
    except ValueError as e:
        not_48_48_images_index.append(i)
        continue


    emotion = emotions[i]
    plt.imsave(f'./{emotion}/{i}.png', img, cmap='gray')

    count = count_image_categories.get(f'{emotion}')
    count += 1
    count_image_categories[f'{emotion}'] = count

print(f'count image: {not_48_48_images_index}')
print(f'{count_image_categories}')


